<a href="https://colab.research.google.com/github/mishraparth/google-collab-notebooks/blob/main/Loan_Sanction_ml.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
df= pd.read_csv('loan_approval_dataset.csv')

In [ ]:
df.head()

,loan_id,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,1,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,2,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,4,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [ ]:
df.drop(columns=['loan_id'], inplace=True)

In [ ]:
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,Graduate,No,9600000,29900000,12,778,2400000,17600000,22700000,8000000,Approved
1,0,Not Graduate,Yes,4100000,12200000,8,417,2700000,2200000,8800000,3300000,Rejected
2,3,Graduate,No,9100000,29700000,20,506,7100000,4500000,33300000,12800000,Rejected
3,3,Graduate,No,8200000,30700000,8,467,18200000,3300000,23300000,7900000,Rejected
4,5,Not Graduate,Yes,9800000,24200000,20,382,12400000,8200000,29400000,5000000,Rejected

In [ ]:
print(df.columns)  # Check if 'education' appears correctly

Index([' no_of_dependents', ' education', ' self_employed', ' income_annum',
       ' loan_amount', ' loan_term', ' cibil_score',
       ' residential_assets_value', ' commercial_assets_value',
       ' luxury_assets_value', ' bank_asset_value', ' loan_status'],
      dtype='object')

In [ ]:
from sklearn.preprocessing import LabelEncoder, StandardScaler
# Encode categorical variables
label_cols = [" education", " self_employed", " loan_status"]
for col in label_cols:
    encoder = LabelEncoder()
    df[col] = encoder.fit_transform(df[col])

In [ ]:
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,9600000,29900000,12,778,2400000,17600000,22700000,8000000,0
1,0,1,1,4100000,12200000,8,417,2700000,2200000,8800000,3300000,1
2,3,0,0,9100000,29700000,20,506,7100000,4500000,33300000,12800000,1
3,3,0,0,8200000,30700000,8,467,18200000,3300000,23300000,7900000,1
4,5,1,1,9800000,24200000,20,382,12400000,8200000,29400000,5000000,1

[0]

In [ ]:
# Normalize numerical columns
num_cols = [" income_annum", " loan_amount", " cibil_score", " residential_assets_value",
            " commercial_assets_value", " luxury_assets_value", " bank_asset_value"]
scaler = StandardScaler()
df[num_cols] = scaler.fit_transform(df[num_cols])

In [ ]:
df.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value,loan_status
0,2,0,0,1.617979,1.633052,12,1.032792,-0.780058,2.877289,0.832028,0.930304,0
1,0,1,1,-0.341750,-0.324414,8,-1.061051,-0.733924,-0.631921,-0.694993,-0.515936,1
2,3,0,0,1.439822,1.610933,20,-0.544840,-0.057300,-0.107818,1.996520,2.407316,1
3,3,0,0,1.119139,1.721525,8,-0.771045,1.649637,-0.381263,0.897943,0.899533,1
4,5,1,1,1.689242,1.002681,20,-1.264055,0.757724,0.735304,1.568075,0.007172,1

In [ ]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [ ]:
Y=df[' loan_status']
X=df.drop(columns=[' loan_status'])

In [ ]:
X.head()

,no_of_dependents,education,self_employed,income_annum,loan_amount,loan_term,cibil_score,residential_assets_value,commercial_assets_value,luxury_assets_value,bank_asset_value
0,2,0,0,1.617979,1.633052,12,1.032792,-0.780058,2.877289,0.832028,0.930304
1,0,1,1,-0.341750,-0.324414,8,-1.061051,-0.733924,-0.631921,-0.694993,-0.515936
2,3,0,0,1.439822,1.610933,20,-0.544840,-0.057300,-0.107818,1.996520,2.407316
3,3,0,0,1.119139,1.721525,8,-0.771045,1.649637,-0.381263,0.897943,0.899533
4,5,1,1,1.689242,1.002681,20,-1.264055,0.757724,0.735304,1.568075,0.007172

In [ ]:
Y.head()

0    0
1    1
2    1
3    1
4    1
Name:  loan_status, dtype: int64

In [ ]:
# Split data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

# Train XGBoost model
model = xgb.XGBClassifier(use_label_encoder=False, eval_metric="logloss")
model.fit(X_train, Y_train)

# Predict
Y_pred = model.predict(X_test)

# Accuracy
print("Model Accuracy:", accuracy_score(Y_test, Y_pred))

/usr/local/lib/python3.11/dist-packages/xgboost/core.py:158: UserWarning: [10:29:27] WARNING: /workspace/src/learner.cc:740:
Parameters: { "use_label_encoder" } are not used.

  warnings.warn(smsg, UserWarning)

Model Accuracy: 0.9824355971896955